### ISSUE TITLE
Couldn't find a valid ICU package installed on the system

### ISSUE THREAD

**Issue by Vincenzoferrara** [AvaloniaUI/Avalonia-VSCode-Extension#12]
as OS I use linux, precisely manjaro

before having this error I had to install asp net runtime 3.1 (although I already had net core, the avalonia app worked even without the package)
I have already installed on my os ICU but it gives me the same error

some links of others who have had this problem and have resolved (unfortunately not for me)
https://github.com/dotnet/vscode-csharp/issues/3952

error log:
process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>, Microsoft.Extensions.Options.IOptionsMonitor`1<Microsoft.Extensions.Logging.LoggerFilterOptions>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolRpcOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>, System.Threading.CancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>)
   at PimpMyAvalonia.LanguageServer.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at PimpMyAvalonia.LanguageServer.Program.Main(System.String[])
   at PimpMyAvalonia.LanguageServer.Program.<Main>(System.String[])
[Info  - 11:16:24] Connection to server got closed. Server will restart.
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>, Microsoft.Extensions.Options.IOptionsMonitor`1<Microsoft.Extensions.Logging.LoggerFilterOptions>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolRpcOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>, System.Threading.CancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>)
   at PimpMyAvalonia.LanguageServer.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at PimpMyAvalonia.LanguageServer.Program.Main(System.String[])
   at PimpMyAvalonia.LanguageServer.Program.<Main>(System.String[])
[Info  - 11:16:24] Connection to server got closed. Server will restart.
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>, Microsoft.Extensions.Options.IOptionsMonitor`1<Microsoft.Extensions.Logging.LoggerFilterOptions>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolRpcOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>, System.Threading.CancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>)
   at PimpMyAvalonia.LanguageServer.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at PimpMyAvalonia.LanguageServer.Program.Main(System.String[])
   at PimpMyAvalonia.LanguageServer.Program.<Main>(System.String[])
[Info  - 11:16:24] Connection to server got closed. Server will restart.
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>, Microsoft.Extensions.Options.IOptionsMonitor`1<Microsoft.Extensions.Logging.LoggerFilterOptions>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolRpcOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>, System.Threading.CancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>)
   at PimpMyAvalonia.LanguageServer.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at PimpMyAvalonia.LanguageServer.Program.Main(System.String[])
   at PimpMyAvalonia.LanguageServer.Program.<Main>(System.String[])
[Info  - 11:16:24] Connection to server got closed. Server will restart.
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>, Microsoft.Extensions.Options.IOptionsMonitor`1<Microsoft.Extensions.Logging.LoggerFilterOptions>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>)
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolRpcOptionsBase`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions..ctor()
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>, System.Threading.CancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(System.Action`1<OmniSharp.Extensions.LanguageServer.Server.LanguageServerOptions>)
   at PimpMyAvalonia.LanguageServer.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[PimpMyAvalonia.LanguageServer.Program+<Main>d__0, PimpMyAvalonia.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at PimpMyAvalonia.LanguageServer.Program.Main(System.String[])
   at PimpMyAvalonia.LanguageServer.Program.<Main>(System.String[])
[Error - 11:16:24] Connection to server got closed. Server will not be restarted.

**Comment by Vincenzoferrara** [comment]
I don't know if it's related or is it a coincidence but after uninstalling PimpMyAvalonia everything gave more error
